train:
  batch_size: 96
  seed: 2021
  epochs: 1000
  num_workers: 4
  restore_path: null
  save_path: checkpoints/finetune/qm9
  log_interval: 20
  lr: 0.0005
  property: homo
  weight_decay: 1e-16
  min_lr: 0.000001

test:
  test_interval: 1

data:
  base_path: datasets/qm9


model:
  name: qm9
  hidden_dim: 128
  attention: true
  n_layers: 7
  max_atom_type: 100
  charge_power: 2
  cutoff: 5.0
  no_edge_types: False
  layernorm: False



